[tool.poetry]
name = "hashindex"
version = "0.5.1"
description = "Find Python objects by exact match on their attributes."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
cykhash = "^2.0.0"
sortednp = "^0.4.0"
sortedcontainers = "^2.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
